[package]
edition = "2021"
name = "wasabi"
version = "0.1.0"

[dependencies]
spin = "0.10.0"

[[bin]]
name = "wasabi"
test = false

[features]
default = []
test = []
test-mode = []

[lib]
crate-type = ["rlib"] # no_std 用ライブラリとしてコンパイル
